DROP TABLE IF EXISTS order_item CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS "order" CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS flyway_schema_history CASCADE;
DROP TYPE IF EXISTS order_status CASCADE;
DROP FUNCTION IF EXISTS update_order_updated_at CASCADE;
