spring:
  application:
    name: supplier-management

  # PostgreSQL Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/supplier-management
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8085

# Logging configuration
logging:
  level:
    com.ssms.suppliermanagement: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"