spring:
  application:
    name: user-management
  
  datasource:
    url: jdbc:postgresql://localhost:5432/ssms_test
    username: postgres
    password: sampath123
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      continue-on-error: false
        
server:
  port: 8081
  
logging:
  level:
    com.ssms.usermanagement: DEBUG
    org.springframework.web: INFO
  