server:
  port: 6543

# URLs for downstream microservices
customer-service:
  url: http://localhost:8081
order-service:
  url: http://localhost:8085
payment-service:
  url: http://localhost:8086 # update this to match the port in payment-management/application.yaml

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/billing
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
