spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ssms_customer
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public

  cloud:
    openfeign:
      client:
        config:
          order-service:
            connect-timeout: 5000
            read-timeout: 5000

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

services:
  order-service:
    url: http://localhost:8084

logging:
  level:
    com.ssms.customerservice: DEBUG
    org.hibernate.SQL: DEBUG