server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ssms_digital_marketing
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
